language: python
sudo: true
matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27-sphinx13
        - TOXENV=py27-sphinx14
        - TOXENV=py27-sphinx15

    - python: 3.5
      env:
        - TOXENV=py35-sphinx13
        - TOXENV=py35-sphinx14
        - TOXENV=py35-sphinx15

    - python: 3.6
      env:
        - TOXENV=lint
        - TOXENV=docs
install:
  - pip install tox
script:
  - tox -e $TOXENV
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
