language: python
python:
  - 2.7
  - 3.5
sudo: true
env:
  - TOX_ENV=py27-sphinx13
  - TOX_ENV=py27-sphinx14
  - TOX_ENV=py35-sphinx13
  - TOX_ENV=py35-sphinx14
  - TOX_ENV=lint
  - TOX_ENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
