language: python
python:
  - 2.7
sudo: true
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=lint
  - TOX_ENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#general
    on_success: change
    on_failure: always
